const BIRD_IDX := 1;
const DEMON_IDX := 2;
const DRAGON_IDX := 3;
//Const EVILMAGE_IDX := 4;
const MALE_IDX := 5;
const FEMALE_IDX := 6;
//Const PIRATE_MALE_IDX := 7;
//Const PIRATE_FEMALE_IDX := 8;
const LIZARD_IDX := 9;
const ORC_IDX := 10;
const OGRE_IDX := 11;
const RATMAN_IDX := 12;

const OBJ_BIRD := 0x6;
const OBJ_DEMON := 0x9;
const OBJ_DEMON_SWORD := 0xa;
const OBJ_DRAGON_RED := 0x3d;
const OBJ_DRAGON_GREY := 0xc;
//Const OBJ_EVILMAGE :=
const OBJ_MALE := 0x190;
const OBJ_FEMALE := 0x191;
//Const OBJ_PIRATE_MALE :=
//Const OBJ_PIRATE_FEMALE :=
const OBJ_LIZARD := 0x21;
const OBJ_LIZARD_MACE := 0x24;
const OBJ_LIZARD_SPEAR := 0x23;

const OBJ_ORC := 0x11;
const OBJ_ORC_CLUB := 0x29;
const OBJ_ORC_CAPT := 0x7;

const OBJ_OGRE := 0x1;

const OBJ_RATMAN := 0x2a;
const OBJ_RATMAN_SWORD := 0x2d;
const OBJ_RATMAN_AXE := 0x2c;