var gotolayout := array(
"page 0",
"nodispose",
"gumppic 0 50 2620",
"gumppic 20 50 2621",
"gumppic 290 50 2622",
"gumppic 0 68 2623",
"gumppic 22 68 2624",
"gumppic 288 68 2625",
"gumppic 0 272 2623",
"gumppic 22 272 2624",
"gumppic 288 272 2625",
"gumppic 0 476 2626",
"gumppic 20 476 2627",
"gumppic 290 476 2628",
"gumppic 20 80 2621",   
"text 20 59 40 0",
"text 260 59 40 1"
);

var gotodata := array(
       "Player Name",         //0
       "Goto"
);

var accountdata := array(
       "Account Name",         //0
       "View"
);