// Speech Event Constants
Const CM_OPEN_BANK		:= "Bank Box";
Const CM_CHECK_BALANCE	:= "Check Balance";
Const CM_VENDOR_BUY		:= "Vendor Buy";
Const CM_VENDOR_SELL	:= "Vendor Sell";
Const CM_DROP			:= "Drop";
Const CM_FOLLOW_ME		:= "Follow Me";
Const CM_GUARD_ME		:= "Guard Me";
Const CM_KILL			:= "Attack";
Const CM_RELEASE		:= "Release";
Const CM_STOP			:= "Stop";
Const CM_STAY			:= "Stay";
Const CM_TRANSFER		:= "Transfer";
Const CM_JOIN			:= "Join";
Const CM_RESIGN			:= "Resign";
Const CM_STABLE			:= "Stable";
