var layout := array(
"page 0",
"gumppic   0  50 0206             ",
"gumppic  40  50 0201             ",
"gumppic 460  50 0207             ",
"gumppic   0  94 0202             ",
"gumppic  40  94 2604             ",
"gumppic 460  94 2605             ",
"gumppic   0 410 2606             ",
"gumppic  40 410 2607             ",
"gumppic 460 410 2608             ",
"gumppic  20 120 5100             ",
"gumppic  28 120 5101             ",
"gumppic 118 120 5101             ",
"gumppic 208 120 5101             ",
"gumppic 298 120 5101             ",
"gumppic 370 120 5101             ",
"gumppic 460 120 5102             ",
"gumppic  20 128 5103             ",
"gumppic  28 128 5104             ",
"gumppic 118 128 5104             ",
"gumppic 208 128 5104             ",
"gumppic 298 128 5104             ",
"gumppic 370 128 5104             ",
"gumppic 460 128 5105             ",
"gumppic  20 136 5058             ",
"gumppic 118 136 5058             ",
"gumppic 232 136 5058             ",
"gumppic 350 136 5058             ",
"gumppic  20 136 5106             ",
"gumppic  28 136 5107             ",
"gumppic 118 136 5107             ",
"gumppic 208 136 5107             ",
"gumppic 298 136 5107             ",
"gumppic 370 136 5107             ",
"gumppic 460 136 5108             ",
"gumppic  28 278 5104             ",
"gumppic 118 278 5104             ",
"gumppic 208 278 5104             ",
"gumppic 298 278 5104             ",
"gumppic 368 278 5104             ",
"gumppic  20 278 5103             ",
"gumppic 460 278 5105             ",
"gumppic  20 226 5058             ",
"gumppic 118 226 5058             ",
"gumppic 232 226 5058             ",
"gumppic 350 226 5058             ",
"gumppic  20 366 5106             ",
"gumppic  28 366 5107             ",
"gumppic 118 366 5107             ",
"gumppic 208 366 5107             ",
"gumppic 298 366 5107             ",
"gumppic 370 366 5107             ",
"gumppic 460 366 5108             ",
"gumppic  20 350 5100             ",
"gumppic  28 350 5101             ",
"gumppic 118 350 5101             ",
"gumppic 208 350 5101             ",
"gumppic 298 350 5101             ",
"gumppic 370 350 5101             ",
"gumppic 460 350 5102             ",
"button  320 410  241  242 1 0 999",
"text    110  80  900    0        ",
"text     30 121    0    1        ",
"text    160 121    0    2        ",
"text    270 121    0    3        ",
"text    370 121    0    4        ",
"text     30 351    0    5        ",
"text    150 351    0    6        ",
"text    300 351    0    7        ",
"text     90 380  900   11        ",
"button   70 384    3    4 1  0 99",
"button  110 123 5209 5209 0  2  0",
"button  230 123 5209 5209 0  3  0",
"button  340 123 5209 5209 0  4  0",
"button  435 123 5209 5209 0  5  0",
"button  100 353 5209 5209 0  6  0",
"button  270 353 5209 5209 0  7  0",
"button  410 353 5209 5209 0  8  0",

"page 2",                            // Page 2 (traps)
"text     70 180  900    8        ",
"text    200 180  900    9        ",
"text    330 180  900   10        ",
"tilepic  80 210 7164             ",
"tilepic 210 210 4414             ",
"tilepic 340 120 14093            ",
"button  120 220  210 211 1 0 4402",
"button  260 220  210 211 1 0 4414",
"button  400 220  210 211 1 0 4345",

"page 3",                            // Page 3 (tools)
"text     70 150  900   51        ",
"text    190 150  900   52        ",
"text    370 150  900   53        ",
"tilepic  80 180 4325             ",
"tilepic 210 180 4028             ",
"tilepic 290 180 3898             ",
"button  120 180  210 211 1 0 4325",
"button  260 180  210 211 1 0 4027",
"button  400 180  210 211 1 0 3897",
"text     70 210  900   54        ",
"text    220 210  900   55        ",
"text    370 210  900   56        ",
"tilepic  80 240 4138             ",
"tilepic 210 240 5091             ",
"tilepic 350 240 4021             ",
"button  120 240  210 211 1 0 4138",
"button  260 240  210 211 1 0 5091",
"button  400 240  210 211 1 0 4020",
"text     70 280  900   57        ",
"text    220 280  900   58        ",
"text    370 280  900   59        ",
"tilepic  80 310 4326             ",
"tilepic 210 310 3718             ",
"tilepic 350 310 5371             ",
"button  120 310  210 211 1 0 4326",
"button  260 310  210 211 1 0 3717",
"button  400 310  210 211 1 0 5371",

"page 4",                            // Page 4 (parts)
"text     70 150  900   21        ",
"text    190 150  900   22        ",
"text    370 150  900   23        ",
"tilepic  80 180 4179             ",
"tilepic 210 180 4175             ",
"tilepic 350 180 4100             ",
"button  120 180  210 211 1 0 4179",
"button  260 180  210 211 1 0 4175",
"button  400 180  210 211 1 0 4100",
"text     70 210  900   24        ",
"text    220 210  900   25        ",
"text    370 210  900   26        ",
"tilepic  80 240 4189             ",
"tilepic 210 240 4185             ",
"tilepic 350 240 4321             ",
"button  120 240  210 211 1 0 4189",
"button  260 240  210 211 1 0 4185",
"button  400 240  210 211 1 0 4321",
"text     70 280  900   27        ",
"tilepic  80 310 4181             ",
"button  120 310  210 211 1 0 4181",

"page 5",                            // Page 4 (utensils)
"text     70 150  900   28        ",
"text    220 150  900   29        ",
"text    370 150  900   30        ",
"tilepic  80 180 5110             ",
"tilepic 198 180 2553             ",
"tilepic 238 180 2552             ",
"tilepic 350 180 2519             ",
"button  120 180  210 211 1 0 5110",
"button  200 180  210 211 1 0 2553",
"button  260 180  210 211 1 0 2552",
"button  400 180  210 211 1 0 2519",
"text     70 210  900  31         ",
"text    220 210  900  32         ",
"text    370 210  900  33         ",
"tilepic  80 240 3781             ",
"tilepic 210 240 2549             ",
"tilepic 220 240 2548             ",
"tilepic 350 240 2458             ",
"button  120 240  210 211 1 0 3781",
"button  200 240  210 211 1 0 2549",
"button  260 240  210 211 1 0 2548",
"button  400 240  210 211 1 0 2458",
"text     70 280  900  34         ",
"text    220 280  900  35         ",
"text    370 280  900  36         ",
"tilepic  80 310 3778             ",
"tilepic 205 310 2551             ",
"tilepic 235 310 2550             ",
"tilepic 350 310 4096             ",
"button  120 310  210 211 1 0 3778",
"button  200 310  210 211 1 0 2551",
"button  260 310  210 211 1 0 2550",
"button  400 310  210 211 1 0 4096",

"page 6",                            // Page 6 (jewelery)
"text     70 150  900  37         ",
"text    190 150  900  38         ",
"text    370 150  900  39         ",
"tilepic  80 180 4234             ",
"tilepic 210 180 4233             ",
"tilepic 350 180 4229             ",
"button  120 180  210 211 1 0 4234",
"button  260 180  210 211 1 0 4233",
"button  400 180  210 211 1 0 4239",
"text     70 210  900  40         ",
"text    220 210  900  41         ",
"text    370 210  900  42         ",
"tilepic  80 240 4231             ",
"tilepic 210 240 4232             ",
"tilepic 350 240 4230             ",
"button  120 240  210 211 1 0 4231",
"button  260 240  210 211 1 0 4232",
"button  400 240  210 211 1 0 4230",

"page 7",                            // Page 7 (miscellaneous)
"text     70 150  900  43         ",
"text    190 150  900  44         ",
"text    370 150  900  45         ",
"tilepic  80 180 4113             ",
"tilepic 210 180 2599             ",
"tilepic 350 180 6225             ",
"button  120 180  210 211 1 0 4113",
"button  260 180  210 211 1 0 2599",
"button  400 180  210 211 1 0 6225",
"text     70 210  900  46         ",
"text    220 210  900  47         ",
"text    370 210  900  48         ",
"tilepic  80 240 4112             ",
"tilepic 210 240 4167             ",
"tilepic 350 240 5365             ",
"button  120 240  210 211 1 0 4112",
"button  260 240  210 211 1 0 4167",
"button  400 240  210 211 1 0 5365",
"text     70 280  900  49         ",
"text    220 280  900  50         ",
"tilepic  80 310 2584             ",
"tilepic 210 310 6217             ",
"button  120 310  210 211 1 0 2597",
"button  260 310  210 211 1 0 6217",

"page 8",                            // Page 3 (more tools)
"text     70 150  900  12         ",
"text    190 150  900  13         ",
"text    370 150  900  14         ",
"tilepic  80 180 3998             ",
"tilepic 210 180 3739             ",
"tilepic 350 180 4327             ",
"button  120 180  210 211 1 0 3998",
"button  260 180  210 211 1 0 3739",
"button  400 180  210 211 1 0 4327",
"text     70 210  900  15         ",
"text    220 210  900  16         ",
"text    370 210  900  17         ",
"tilepic  80 240 7865             ",
"tilepic 210 240 3907             ",
"tilepic 350 240 4324             ",
"button  120 240  210 211 1 0 7865",
"button  260 240  210 211 1 0 3907",
"button  400 240  210 211 1 0 4324",
"text     70 280  900  18         ",
"text    220 280  900  19         ",
"text    370 280  900  20         ",
"tilepic  80 310 3997             ",
"tilepic 210 310 4148             ",
"tilepic 350 310 4136             ",
"button  120 310  210 211 1 0 3997",
"button  260 310  210 211 1 0 4148",
"button  400 310  210 211 1 0 4136"
);

var data := {
  "TINKER SELECTION MENU",           // 0
  "Traps",                           // 1
  "Tools",                           // 2
  "Parts",                           // 3
  "Utensils",                        // 4
  "Jewelery",                        // 5
  "Miscellaneous",                   // 6
  "More Tools",                      // 7
  "Dart Trap",                       // 8
  "Poison Trap",                     // 9
  "Explosion Trap",                  // 10
  "Make Last",                       // 11
  "scissors",                        // 12
  "mortar & pestle",                 // 13
  "scorp",                           // 14
  "tinker's tools",                  // 15
  "hatchet",                         // 16
  "draw knife",                      // 17
  "sewing kit",                      // 18
  "saw",                             // 19
  "dovetail saw",                    // 20
  "gears",                           // 21
  "clock parts",                     // 22
  "keg tap",                         // 23
  "springs",                         // 24
  "sextant parts",                   // 25
  "barrel hoops",                    // 26
  "hinge",                           // 27
  "butcher knife",                   // 28
  "spoons",                          // 29
  "plate",                           // 30
  "skinning knife",                  // 31
  "forks",                           // 32
  "goblet",                          // 33
  "cleaver",                         // 34
  "knives",                          // 35
  "pewter mug",                      // 36
  "ring",                            // 37
  "necklace",                        // 38
  "necklace",                        // 39
  "earrings",                        // 40
  "necklace",                        // 41
  "bracelet",                        // 42
  "keyring",                         // 43
  "candelabra",                      // 44
  "scales",                          // 45
  "iron key",                        // 46
  "globe",                           // 47
  "spy glass",                       // 48
  "lantern",                         // 49
  "heating stand",                   // 50
  "froe",                            // 51
  "tongs",                           // 52
  "shovel",                          // 53
  "hammer",                          // 54
  "smith's hammer",                  // 55
  "sledge hammer",                   // 56
  "inshave",                         // 57
  "pickaxe",                         // 58
  "lockpick"                         // 59
};

var wlayout := array(
"page 0",
"gumppic   0  50 0206             ",
"gumppic  40  50 0201             ",
"gumppic 460  50 0207             ",
"gumppic   0  94 0202             ",
"gumppic  40  94 2604             ",
"gumppic 460  94 2605             ",
"gumppic   0 410 2606             ",
"gumppic  40 410 2607             ",
"gumppic 460 410 2608             ",
"gumppic  20 120 5100             ",
"gumppic  28 120 5101             ",
"gumppic 118 120 5101             ",
"gumppic 208 120 5101             ",
"gumppic 298 120 5101             ",
"gumppic 370 120 5101             ",
"gumppic 460 120 5102             ",
"gumppic  20 128 5103             ",
"gumppic  28 128 5104             ",
"gumppic 118 128 5104             ",
"gumppic 208 128 5104             ",
"gumppic 298 128 5104             ",
"gumppic 370 128 5104             ",
"gumppic 460 128 5105             ",
"gumppic  20 136 5058             ",
"gumppic 118 136 5058             ",
"gumppic 232 136 5058             ",
"gumppic 350 136 5058             ",
"gumppic  20 136 5106             ",
"gumppic  28 136 5107             ",
"gumppic 118 136 5107             ",
"gumppic 208 136 5107             ",
"gumppic 298 136 5107             ",
"gumppic 370 136 5107             ",
"gumppic 460 136 5108             ",
"gumppic  28 278 5104             ",
"gumppic 118 278 5104             ",
"gumppic 208 278 5104             ",
"gumppic 298 278 5104             ",
"gumppic 368 278 5104             ",
"gumppic  20 278 5103             ",
"gumppic 460 278 5105             ",
"gumppic  20 226 5058             ",
"gumppic 118 226 5058             ",
"gumppic 232 226 5058             ",
"gumppic 350 226 5058             ",
"gumppic  20 366 5106             ",
"gumppic  28 366 5107             ",
"gumppic 118 366 5107             ",
"gumppic 208 366 5107             ",
"gumppic 298 366 5107             ",
"gumppic 370 366 5107             ",
"gumppic 460 366 5108             ",
"gumppic  20 350 5100             ",
"gumppic  28 350 5101             ",
"gumppic 118 350 5101             ",
"gumppic 208 350 5101             ",
"gumppic 298 350 5101             ",
"gumppic 370 350 5101             ",
"gumppic 460 350 5102             ",
"button  320 410  241  242 1 0 999",
"text    150  80  900    0        ",
"text     90 380  900    6        ",
"text     70 150  900    1        ",
"text    190 150  900    2        ",
"text    350 150  900    3        ",
"tilepic  80 180 4144             ",
"tilepic 210 180 4140             ",
"tilepic 350 180 4146             ",
"button  120 180  210 211 1 0 4144",
"button  260 180  210 211 1 0 4140",
"button  390 180  210 211 1 0 4146",
"text     70 210  900    4        ",
"text    220 210  900    5        ",
"tilepic  80 240 4173             ",
"tilepic 210 240 4187             ",
"button  120 240  210 211 1 0 4173",
"button  260 240  210 211 1 0 4187",
"button   70 384    3    4 1  0 99"
);

var wdata := {
  "WOODEN ITEM MENU",                // 0
  "Jointing Plane",                  // 1
  "Moulding Plane",                  // 2
  "Smoothing Plane",                 // 3
  "Clock Frame",                     // 4
  "Axle",                            // 5
  "Make Last"                        // 6
};