////////////////////////////////
// htmlgumpcolor Color Values
////////////////////////////////
Const HTML_BLACK          := "#000000";
Const HTML_DARKGRAY       := "#696969";//"#404040";
Const HTML_GRAY           := "#808080";
Const HTML_LIGHTGRAY      := "#C0C0C0";
Const HTML_DARKSLATEGRAY  := "#2F4F4F";
Const HTML_SLATEGRAY      := "#708090";
Const HTML_LIGHTSLATEGRAY := "#778899";
Const HTML_DARKRED        := "#800000";
Const HTML_RED            := "#FF0000";
Const HTML_DARKGREEN      := "#008000";
Const HTML_GREEN          := "#00FF00";
Const HTML_DARKYELLOW     := "#808000";
Const HTML_YELLOW         := "#FFFF00";
Const HTML_DARKORANGE     := "#FF8C00";
Const HTML_DARKBLUE       := "#000080";
Const HTML_BLUE           := "#0000FF";
Const HTML_DARKPURPLE     := "#800080";
Const HTML_PURPLE         := "#FF00FF";
Const HTML_DARKTURQUOISE  := "#008080";
Const HTML_TURQUOISE      := "#00FFFF";
Const HTML_WHITE          := "#FFFFFF";
Const HTML_SADDLEBROWN    := "#8B4513";

////////////////////////////////
// xmfhtmlgumpcolor Color Values
////////////////////////////////
Const XMFCOLOR_BLACK          :=0;
Const XMFCOLOR_WHITE          :=32767;
Const XMFCOLOR_BLUE1          :=15;
Const XMFCOLOR_BLUE2          :=5295;
Const XMFCOLOR_RED1           :=15360;
Const XMFCOLOR_RED2           :=20480;
Const XMFCOLOR_RED3           :=25600;
Const XMFCOLOR_RED4           :=30720;
Const XMFCOLOR_RED5           :=32000;
Const XMFCOLOR_RED6           :=32272;
Const XMFCOLOR_RED7           :=64512;
Const XMFCOLOR_GRAYRED        :=16715;
Const XMFCOLOR_PURPLE1        :=16927;
Const XMFCOLOR_PURPLE2        :=19777215;
Const XMFCOLOR_GRAY1          :=15855;
Const XMFCOLOR_GRAY2          :=16912;
Const XMFCOLOR_OCHER1         :=23341;
Const XMFCOLOR_OCHER2         :=49671;
Const XMFCOLOR_OCHER3         :=90000;
Const XMFCOLOR_GREEN1         :=33280;
Const XMFCOLOR_GREEN2         :=33760;
Const XMFCOLOR_YELLOW         :=32512;
Const XMFCOLOR_TURQUOISE      :=1023;
Const XMFCOLOR_TURQUOISEGREEN :=10000;