use uo;
use os;
use util;

function RandomPinkHue()

	return RandomIntMinMax( 1201, 1255 );
endfunction

function RandomBlueHue()

	return RandomIntMinMax( 1301, 1355 );
endfunction

function RandomGreenHue()

	return RandomIntMinMax( 1401, 1455 );
endfunction

function RandomOrangeHue()

	return RandomIntMinMax( 1501, 1555 );
endfunction

function RandomRedHue()

	return RandomIntMinMax( 1601, 1655 );
endfunction

function RandomYellowHue()

	return RandomIntMinMax( 1701, 1755 );
endfunction

function RandomNeutralHue()

	return RandomIntMinMax( 1801, 1909 );
endfunction

function RandomDyedHue()

	return RandomIntMinMax( 2, 1001 );
endfunction
