/**
 * Localizable data constants. Do not localize constant names, but
 * you can localize the string values.
 *
 * @author     Andromeda UO
 * @author     Jouni Airaksinen, mintus@andromeda-uo.net
 * @url        http://www.andromeda-uo.net/
 * @version    1.0 (%G%)
 * @copyright  (C) Copyright 2002-2003
 */
 
// constants //

const DateSeparator := "-";
const TimeSeparator := ":";

const SShortMonthNameJan := "Jan";
const SShortMonthNameFeb := "Feb";
const SShortMonthNameMar := "Mar";
const SShortMonthNameApr := "Apr";
const SShortMonthNameMay := "May";
const SShortMonthNameJun := "Jun";
const SShortMonthNameJul := "Jul";
const SShortMonthNameAug := "Aug";
const SShortMonthNameSep := "Sep";
const SShortMonthNameOct := "Oct";
const SShortMonthNameNov := "Nov";
const SShortMonthNameDec := "Dec";

const SLongMonthNameJan := "January";
const SLongMonthNameFeb := "February";
const SLongMonthNameMar := "March";
const SLongMonthNameApr := "April";
const SLongMonthNameMay := "May";
const SLongMonthNameJun := "June";
const SLongMonthNameJul := "July";
const SLongMonthNameAug := "August";
const SLongMonthNameSep := "September";
const SLongMonthNameOct := "October";
const SLongMonthNameNov := "November";
const SLongMonthNameDec := "December";

const SShortDayNameSun := "Sun";
const SShortDayNameMon := "Mon";
const SShortDayNameTue := "Tue";
const SShortDayNameWed := "Wed";
const SShortDayNameThu := "Thu";
const SShortDayNameFri := "Fri";
const SShortDayNameSat := "Sat";

const SLongDayNameSun := "Sunday";
const SLongDayNameMon := "Monday";
const SLongDayNameTue := "Tuesday";
const SLongDayNameWed := "Wednesday";
const SLongDayNameThu := "Thursday";
const SLongDayNameFri := "Friday";
const SLongDayNameSat := "Saturday";

