const OBJ_BIRD := 0x6;
const OBJ_DAEMON := 0x9;
const OBJ_DAEMON_SWORD := 0xA;
const OBJ_DRAGON_RED := 0x3D;
const OBJ_DRAGON_GREY := 0xC;
const OBJ_MALE := 0x190;
const OBJ_FEMALE := 0x191;
const OBJ_LIZARD := 0x21;
const OBJ_LIZARD_MACE := 0x24;
const OBJ_LIZARD_SPEAR := 0x23;

const OBJ_ORC := 0x11;
const OBJ_ORC_CLUB := 0x29;
const OBJ_ORC_CAPT := 0x7;

const OBJ_OGRE := 0x1;

const OBJ_RATMAN := 0x2A;
const OBJ_RATMAN_SWORD := 0x2D;
const OBJ_RATMAN_AXE := 0x2C;
